project:
  type: book
  output-dir: docs
  
lightbox: true

language:
  section-title-appendices: "Приложения"
  
citation: 
  url: https://agoroshko.github.io/qgis_for_beginners

book:
  title: "Основы геоинформационных систем в QGIS"
  subtitle: "Геоинформационные системы в лесном хозяйстве"

  author:
  - name: Андрей Горошко
    affiliation: СибГУ им. М.Ф. Решетнева
    affiliation-url: https://www.sibsau.ru/
  - name: Ирина Воробьева
    affiliation: СибГУ им. М.Ф. Решетнева
    affiliation-url: https://www.sibsau.ru/
  - name: Виктор Немич
    affiliation: СибГУ им. М.Ф. Решетнева
    affiliation-url: https://www.sibsau.ru/
  
  date: today
  license: Лицензия
  doi: 10.5281/zenodo.10034638
  chapters:
    - index.qmd
    - chapter0_resources.qmd
    - chapter1_georeferencing.qmd
    - chapter2_vectorization.qmd
    - chapter3_attributes.qmd
    - chapter4_thematic_maps.qmd
    - chapter5_queries.qmd
    - chapter6_spatial_operations.qmd
    - chapter7_OSM.qmd
    - chapter8_DEM.qmd
    - references.qmd
  appendices:
    - appendice_1_geopackage.qmd
    - appendice_2_epsg_3857.qmd
    - appendice_3_csv.qmd
  navbar: 
    logo: "./cover.png"
    
  page-navigation: true

crossref:
  custom:
    - kind: float
      reference-prefix: Видео
      caption-prefix: Видео
      key: vid
    - kind: float
      reference-prefix: Задание
      caption-prefix: Задание
      key: task
      
bibliography: references.bib
number-sections: true

format:
  html:
    theme:
      light: 
        - cosmo
      dark: 
        - solar
    lang: ru
    number-sections: true
  pdf:
    documentclass: scrreprt



