project:
  type: book
  output-dir: docs

language:
  section-title-appendices: "Приложения"

book:
  title: "Основы геоинформационных систем в QGIS"
  subtitle: "Геоинформационные системы в лесном хозяйстве"
  author: "Андрей Горошко, Ирина Воробьева, Виктор Немич"
  date: today
  license: Лицензия
  doi: 10.5281/zenodo.10034638
  chapters:
    - index.qmd
    - chapter0_resources.qmd
    - chapter1_georeferencing.qmd
    - chapter2_vectorization.qmd
    - chapter3_attributes.qmd
    - chapter4_thematic_maps.qmd
    - chapter5_queries.qmd
    - chapter6_spatial_operations.qmd
    - chapter7_DEM.qmd
    - chapter8_satellite_data.qmd
    - references.qmd
  appendices:
    - application_1_geopackage.qmd
  navbar: 
    logo: "./cover.png"


bibliography: references.bib
number-sections: true

format:
  html:
    theme: cosmo
    lang: ru
    number-sections: true
  pdf:
    documentclass: scrreprt



