project:
  type: book
  output-dir: docs
  
lightbox: true

language:
  section-title-appendices: "Приложения"

book:
  title: "Основы геоинформационных систем в QGIS 3.28"
  subtitle: "Геоинформационные системы в лесном хозяйстве"
  author: "Андрей Горошко, Ирина Воробьева, Виктор Немич"
  date: today
  license: Лицензия
  doi: 10.5281/zenodo.10034638
  chapters:
    - index.qmd
    - chapter0_resources.qmd
    - chapter1_georeferencing.qmd
    - chapter2_vectorization.qmd
    - chapter3_attributes.qmd
    - chapter4_thematic_maps.qmd
    - chapter5_queries.qmd
    - chapter6_spatial_operations.qmd
    - chapter7_DEM.qmd
    - chapter8_satellite_data.qmd
    - references.qmd
  appendices:
    - appendice_1_geopackage.qmd
    - appendice_2_epsg_3857.qmd
  navbar: 
    logo: "./cover.png"

crossref:
  custom:
    - kind: float
      reference-prefix: Видео
      caption-prefix: Видео
      key: vid
    - kind: float
      reference-prefix: Задание
      caption-prefix: Задание
      key: task
      
bibliography: references.bib
number-sections: true

format:
  html:
    theme: cosmo
    lang: ru
    number-sections: true
  pdf:
    documentclass: scrreprt



