project:
  type: book
  output-dir: docs

book:
  title: "Основы геоинформационных систем в QGIS"
  subtitle: "Геоинформационные системы в лесном хозяйстве"
  author: "Андрей Горошко, Ирина Воробъева, Виктор Немич"
  date: today
  license: Лицензия
  chapters:
    - index.qmd
    - chapter0_resources.qmd
    - chapter1_georeferencing.qmd
    - chapter2_vectorization.qmd
    - chapter3_attributes.qmd
    - chapter4_thematic_maps.qmd
    - chapter5_queries.qmd
    - chapter6_spatial_operations.qmd
    - appendix_1_geopackage.qmd
    - references.qmd
  navbar: 
    logo: "./cover.png"

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: ru
    number-sections: true
  pdf:
    documentclass: scrreprt



