# Системы координат {#sec-crs}



## Описание СК WGS 84 / Pseudo-Mercator (EPSG:3857)

## ГСК 2011


## Местные системы координат

Местные системы координат (МСК) используются при кадастровых работах.
Список МСК для Красноярского края приведен ниже (источник https://terraingis.ru/msk-24.html).

Распределение кадастровых районов по расчетным местным системам координат и зонам следующее:

    Диксонский (84:01), Усть-Енисейский (84:04) – MCK-163, Зона 1;
    Typyxaнский (24:37) – МCK-164, Зона 1;
    Диксонский (84:01), Дудинский (84:02), Усть-Енисейский (84:04) – MCK-164, Зона 2;
    Typyxaнский (24:37), г. Игарка (24:49), г. Hopильск (24:55) – MCK-165, Зона 2;
    Диксонский (84:01), Дудинский (84:02), г. Дудинка (84:03), Усть-Енисейский (84:04) – MCK-165, Зона 3;
    Ачинский (24:02), Балахтинский (24:03), Бирилюсский (24:05), Боготольский (24:06), Большеулуйский (24:09), Енисейский (24:12), Козульский (24:21), Назаровский (24:27), Новоселовский (24:29), Typyxaнский (24:37), Тюхтетский (24:38), Ужурский (24:39), Шарыповский (24:41), г. Aчинск (24:43), г. Боготол (24:44), г. Haзарово (24:54), г. Шарыпово (24:57), 3ATO п. Солнечный (24:61) – MCK-166, Зона 3;
    Дудинский (84:02) – MCK-166, Зона 4;
    Условный кадастровый (24:00), Балахтинский (24:03), Березовский (24:04), Енисейский (24:12), Ермаковский (24:13), Идринский (24:14), Казачинский (24:17), Каратузский (24:19), Краснотуранский (24:22), Курагинский (24:23), Манский (24:24), Минусинский (24:25), Мотыгинский (24:26), Партизанский (24:30), Пировский (24:31), Север-Енисейский (24:34), Cyxo6yзимский (24:35), Уярский (24:40), Шушенский (24:42), г. Дивногорск (24:46), г. Eнисейск (24:47), г. Красноярск (24:50), г. Лесосибирск (24:52), г. Минусинск (24:53), г. Cocнoвo6opcк (24:56), 3ATO г. Железногорск (24:58), п. Кeдровый (24:60), Диксонский (84:01), Дудинский (84:02), Илимпийский (88:01), Байкитский (88:02), Большемуртинский (24:08), Емельяновский (24:11) – MCK-167, Зона 4;
    Абанский (24:01), Богучанский (24:07), Дзержинский (24:10), Иланский (24:15), Ирбейский (24:16), Канский (24:18), Мотыгинский (24:26), Нижнеингашский (24:28), Рыбинский (24:32), Саянский (24:33), Tacаевский (24:36), г. Бородино (24:45), г. 3aoзерный (24:48), г. Kaнск (24:51), 3ATO г. Зеленогорск (24:59) — MCK-168, Зона 5;
    Условный кадастровый (84:00), Диксонский (84:01), Дудинский (84:02) – MCK-168, Зона 6;
    Илимпийский ( 88:01), Байкитский (88:02) – MCK-168, Зона 2;
    Богучанский (24:07), Кужемский (24:20) – MCK-169, Зона 6;
    Диксонский (84:01), Хатангский (84:05) – MCK-169, Зона 7;
    Условный кадастровый (88 :00), Илимпийский (88:01), Илимпийский (88:01), Байкитский (88:02) – MCK-169, Зона 3;
    Кужемский (24:20) – MCK-170, Зона 7;
    Хатангский (84:05) – MCK-170, Зона 8;
    Илимпийский ( 88:01), Тунгусско-Чунский (88:03) – MCK-170, Зона 4;
    Диксонский (84:01), Хатангский (84:05) – MCK-171, Зона 9;
    Илимпийский (88:01), Тунгусско-Чунский (88:03) – MCK-171, Зона 5;
    Хатангский (84:05) – MCK-172, Зона 10;
    Хатангский (84:05) — MCK-173, Зона 11.


МСК г. Красноярска
+proj=tmerc +lat_0=0 +lon_0=93 +k=1 +x_0=54304.47 +y_0=-6196680.59 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs


МСК-163
+proj=tmerc +lat_0=0 +lon_0=81 +k=1 +x_0=65425.7 +y_0=-7434483.2 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs

МСК-164
+proj=tmerc +lat_0=0 +lon_0=84 +k=1 +x_0=86209.8 +y_0=-6542783.5 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs

МСК-165
+proj=tmerc +lat_0=0 +lon_0=87 +k=1 +x_0=105295.8 +y_0=-5652185. +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs

МСК-166
+proj=tmerc +lat_0=0 +lon_0=90 +k=1 +x_0=107543.3 +y_0=-5540944.5 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs

МСК-167
+proj=tmerc +lat_0=0 +lon_0=93 +k=1 +x_0=106797.8 +y_0=-5578022.5 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs

МСК-168
+proj=tmerc +lat_0=0 +lon_0=96 +k=1 +x_0=108285.2 +y_0=-5503868.6 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs

МСК-169
+proj=tmerc +lat_0=0 +lon_0=99 +k=1 +x_0=117308.6 +y_0=-5503868.6 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs

МСК-170
+proj=tmerc +lat_0=0 +lon_0=102 +k=1 +x_0=90338.90 +y_0=-6357146.10 +ellps=krass +towgs84=23.57,-140.95,-79.8,0,0.35,0.79,-0.22 +units=m +no_defs