# Формат данных CSV {#sec-csv}

CSV (Comma-Separated Values) - [формат для представления табличных данных в виде текста](https://ru.wikipedia.org/wiki/CSV). Каждая строка в файле - строка в таблице, столбцы внутри строки отделяются друг от друга специальным символом - разделителем (delimiter). Несмотря на название формата, разделителем не обязательно должна быть запятая, более того, основное условие выбора символа-разделителя: он не должен встречаться в значениях таблицы. Если в таблице встерчаются дробные числа, где целая часть отделена запятой, нельзя использовать в качестве разделится запятую. Часто в таких случаях используют символ табуляции (`\t`) в качестве разделителя. Выбрать разделитель возможно при сохранении таблицы в формат **.csv** в любом табличном редакторе.  

После сохранения **.csv** файла, в QGIS выберите пункт меню **"Слой" > "Добавить слой" > "Добавить слой из текста с разделителями..."**. В пункте "Имя файла" укажите путь к файлу **.csv**.  Задайте тип разделителя: пункт **"Формат файла" > "Другие разделители" > чек-бокс "Табуляция"** (или иной разделитель, выбранный при сохранении файла). В пункте **"Пример данных"** убедитесь что таблица соответсвует желаемому результату (там же возможно настроить типы данных столбцов).  

Пункт **"Параметры записей и полей"** позволяет более детально настроить данные таблицы в частности выбрать запятую в качестве десятичного разделителя. Если таблица содержит координаты точечных объектов (столбцы с координатами x и y) возможно импортировать файл в виде точечного слоя. Для этого в пункте **"Формат геометрии" > "Координаты точки"** выберите столбцы из таблицы, соотвествующие координатам (пункты "Поле X" и "Поле Y") и систему координат (пункт "Система координат геометрии"). Если таблица не содержит координат, отметьте пункт **"Без геометрии (только атрибуты)"**. Провертьте пункт "Примеры данных", таблица должна соответствовать желаемуому результату, после чего нажмите "Добавить".



**!!Добавить видео экспорта-импорта таблицы!!**



