# Формат данных GeoPackage {#sec-gpkg}

Каждый файл GeoPackage (.gpkg) является базой данных SQLite с поддержкой [следующих данных](https://www.geopackage.org/):

* векторные геометрии;
* растровые данные;
* таблицы атрибутов (без геометрий).

В отличие от шейп-файлов, которые представлены набором отдельных файлов работающих вместе (.shp, .shx, .dbf и т.д.), файл GeoPackage является единственным файлом с расширением **.gpkg**. Более того, один файл способен хранить в себе несколько слоев данных (при использовании шейп-файлов каждый слой должен храниться отдельно), а объем файла не ограничен (шейп-файлы ограничены объемом 2 GB). С подробным сравнением форматов можно ознакомиться по [ссылке](https://mapscaping.com/shapefiles-vs-geopackage/).  
Несмотря на преимущества формата GeoPackage, он не так распростанен как шейп-файлы. В QGIS процесс работы с данными несущественно зависит от формата их хранения, за исключением одной особенности. При работе с файлами GeoPackage каждый векторный слой имеет ключь - поле **fid** которое содержит уникальное натуральное число для каждой строки таблицы атрибутов. Если такое поле не создано, после сохранения файла оно будет добавлено автоматически. При редактировании геометрий объектов, в поле могут появляться повторяющиеся значения. Такой слой не может быть сохранен, о чем программа предупредит пользователя. Для исправления ошибки устраните дубликаты в поле **fid** (отсутствующие значения так же недопустимы) или удалите поле полностью. В последнем случае оно будет автоматически добавлено после сохранения слоя.

**!Добавить видео исправления ошибки в поле fid!**



