# Поиск объектов по атрибутивной информации и пространственному положению {#sec-queries}


```{r}
#| echo: false

# Нумерация заданий
ch <- 5 # Номер главы
t <- 1 # Номер первого задания (task)

task_fun <- function(ch, t){
  # Функция для добавление номера к заданию
  t <<- t+1
  paste(ch, t, sep = ".")
}

# Пример заголовка задания
## Задание `r task_fun(ch, t)`
```

Распространенной задачей в геоинформационных системах является поиск объектов по характеристикам (атрибутам) и пространственному положению. Для решения этой задачи пользуются логическими выражениями (предикатами) которые отделают искомые объекты от всех остальных. Аналогичные выражения уже использовались в @sec-rules. Для поиска объектов используется "Панель выбора объектов", активировать которую можно в меню **"Вид" > "Панели инструментов" > "Панель выбора объектов"**.


Описание таблицы атрибутов добавить.


## Выбор объектов по значению


Простой способ выбора объектов по атрибутов реализуется при помощи инструмента "Выбрать объекты по значению". В открывшемся окне представлен список полей слоя для каждого из которых возможно задать определенный фильтр. По умолчанию для всех полей активирован режим **"Исключить поле"** т.е. поле не участвует в фильтрации. Для текстовых полей дополнительная настройка **"Case sensetive"** включает чувствительность к регистру. Список доступных логических операций различен для текстовых и числовых полей.

!Добавить рисунок логических операций (для текстового и числового поля, 2 картинки)

Фильтр настраивается путем введения порогового значения в необходимое поле и выбора логической операции (равно, больше, меньше и т.д.). Все объекты удовлетворяющие условию будут выбраны. Фильтрация по нескольким полям объединяется оператором **"И"** т.е. будут выбраны объекты удовлетворяющие всем условиям. Фильтр для отбора выделов с преобладающей породой сосна и возрастом более 100 лет приведен на рисунке.

!Рисунок. Фильтр объектов. сосна более 100 лет

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
При помощи инструмента "Выбор объектов по значению", выберите выдела с преобладающей породой береза (поле "el_lesa"), типом леса "ВРТ" (поле "tip_lesa") и средним возрастом более 80 лет (поле "A_let"). В результате должно быть выбрано 42 выдела.
:::

После выделения объектов их можно сохранить как отдельный слой, для этого перейдите в пункт меню «Правка» и выбирете пункт «Копировать объекты», после чего перейдите в тот же пунк «Правка» - «Вставить объекты как» - выберите пункт «Новый векторный слой». Сохраните новый слой в рабочую папку проекта. Теперь созданный слой содержит только выделенные объекты.

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
Сохраните выделенные объекты из предыдущего задания как новый векторный слой.
:::

Кроме опции "Выбрать объекты" доступны варианты модификации ранее выбранных объектов. "Добавить к текущей выборке" и "Удалить из текущей выборки" позволяют соответственно добавить или удлить отфильтрованные объекты из выбранных ранее, "Фильтровать текущую выборку" применяет фильтр к ранее выбранным объектам.

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
Выберите 20 - 30 случайных выделов, используя инструмент "Выбор объектов" (!!добавить иконку!!). Отфильтруйте полученную выборку так, что бы остались выдела с преобладанием сосны (поле "el_lesa"). Для этого используйте инструмент "Выбрать по значению" > "Фильтровать текущую выборку". 
:::


## Выбор объектов по выражению


Более гибкие возможности выбора объектов предоставляет инструмент "Выбрать объекты по выражению...".

Картинка окна.

В левой части окна записывается логическое выражение (предикат). В средней части выбираются логические операторы и поля, участвующие в выражении (категории "Операторы" и "Поля и значения"). В правой части окна выводится справка по функциям. Иконка "Выбрать объекты" активирует выбор объектов по заданному выражению. Операторы для количественных и качественных переменных различаются. Для запросов к количественным переменным (площадь выдела, средний возраст и т.д.) применяются операторы: равно (=), не равно (<>), больше (>), меньше (<), больше или равно (>=), меньше или равно (<=). Для запросов к качественным переменным (элемент леса, тип леса и т.д.) используют операторы **IS, IS NOT, IN**.  
Выражение для выбора выделов с площадью более 5 га: "s_ga" > 5. Выражение для выбора выделов с типом леса "ВКТ": **"tip_lesa"  IS  'БРТ'**. Выражение для выбора выделов где преобладающая порода НЕ сосна: **"el_lesa" IS NOT 'С'**.

::: {.callout-note}
## Обратите внимание!
В конструкторе выражений названия полей записываются в двойных кавычках ("s_ga"), текст в одинарных ('БРТ').
:::

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
При помощи инструмента "Выбрать по выражению" выберите выдела 1 группы возраста (поле "gr_vozr"). В результате должно быть выбрано 9 выделов.
:::

Пропущенные значения кодируются значением NULL.

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
При помощи инструмента "Выбрать по выражению" выберите выдела в которых пропущен запас на 1 га (поле "zapas_1ga"). В результате должно быть выбрано 64 выдела.
:::

Отдельная группа операторов позволяет объединить несколько условий в единое выражение, соединяя их одним из операторов: И (AND); ИЛИ (OR). Отдельно стоит рассмотреть оператор NOT, который меняет результат любого оператора на противоположный. Все перечисленные операторы могут принимать только два значения: правда или ложь. Если для конкретного объекта всё выражение принимает значение правда — этот объект соответствует условиям и попадает в выборку.  
Для выбора выделов со средним возрастом от 50 до 70 лет конструируется следующее выражение: "A_let" > 50 **AND** "A_let" < 70. В этом случае было записано два условия соединенных через оператор «AND» (И). Такое выражение выбирает объекты, которые соответствуют **И** первому **И** второму условию.

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
При помощи инструмента "Выбрать по выражению" выберите выдела со средним диаметром больше 40 см (поле "DBH_cm") **И** преобладающей породой сосна. В результате должен быть выбран 21 выдел.
:::

Для объединения нескольких условий так же применяется оператор **"OR"** который используется когд объект должен удовлетворять хотя бы одному условию. Например, для выбора выделов со средней высотой более 30 м **ИЛИ** возрастом более 100 лет используется выражение: "H_m" > 30 **OR** "A_let" > 100.

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
При помощи инструмента "Выбрать по выражению" выберите выдела с преобладающей породой осина **ИЛИ** выдела старше 140 лет. В результате должно быть выбрано 38 выделов.
:::

Для выбора нескольких значений качественной переменной используется оператор **IN** после которого в круглых скобках указывается список значений. Если значение атрибута соответствует хотя бы одному значению из списка - выдел попадает в выборку. Выбор выделов с типами леса ВКТ, ЗМ или КТП производится выражением: "tip_lesa" **IN** ('ВКТ', 'ЗМ', 'КТП').

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
При помощи инструмента "Выбрать по выражению" выберите выдела с преобладающей породой березой, осиной или липой возрастом более 60 лет. В результате должно быть выбрано 59 выделов.
:::


## Выбор объектов по пространственному положению


Выбор объектов по пространственному положению производится инструментом **"Выбрать по расположению"** который позволяет выбрать объекты одного слоя по пространственным отношениям к объектам другого слоя.

!Добавить рисунок

В пункте **"Выбрать объекты слоя"** назначается слой из которого выбираются объекты по условию пространственного отношения с другим слоем, который задается в пункте **"по отношению к объектам слоя"**. Необходимые пространственные отношения отмечаются чек-боксом в пункте **"Геометрический предикат"**. Пункт "Изменить текущую выборку" позволяет "создать новую выборку" или модифицировать уже выбранные объекты: "добавить к текущей выборке"; "выбрать в текущей выборке" или "удалить из текущей выборки". Использование этой настройки позволяет проводить отбор объектов на основе атрибутивной информации и по пространственным отношениям.

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
Используя инструмент **"Выбрать по расположению"**, выберите только те выдела, которые пересекаются реками. Сохраните выдела как отдельный слой.
:::

Пункт "Изменить текущую выборку" позволяет "создать новую выборку" (по умолчанию) или модифицировать уже существующую: "добавить к текущей выборке", "выбрать в текущей выборке", "удалить из текущей выборки". Последние 3 пункта позволяют объединить несколько пространственных запросов или комбинировать пространственный запрос с выбором по атрибутам.

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
Выберите выдела которые пересекаются реками или дорогами. Для этого объедините два пространственных запроса. В результате должен быть выбран 151 выдел. Сохраните выбранные объекты как новый векторный слой.
:::

::: {.callout-tip}
## Задание `r task_fun(ch, t)`
Выберите выдела которые пересекаются реками и преобладающая порода в которых не сосна. Для этого объедините пространственный запрос с запросом по атрибутам. В результате должно быть выбрано 19 выделов. Сохраните выбранные объекты как новый векторный слой.
:::


