# Мобильное приложение QField

Использование гис для мобильных устройств (смартфонов и планшетов) особенно удобно при выполнении полевых работ. Чаще всего мобильные ГИС выполняют 2 основные функции:

+ Ориентирование на местности. Поскольку прием GNSS сигнала не требует подключения к телефонной сети или интернету, ориентирование на местности возможно проводить в самых удаленных районах.

+ Сбор полевых данных. Большинство приложений позволяет добавлять новую информацию в ГИС на мобильном устройстве. Чаще всего это координаты объектов, атрибутивная информация, фотография. После записи, данные с мобильного устройства синхронизируются с базой данных на компьютере. Некоторые решения предлагают совместную работу и синхронизацию данных с нескольких устройств.

Мобильные ГИС приложение, как правило, интегрированы с тем или иным десктопным приложением. Такие пары образуют ArcGIS - ArcGIS Field Maps, NextGIS - NextGIS Mobile. Для QGIS существуют два приложения для мобильных устройств: [MerginMaps](https://merginmaps.com/) и [QField](https://qfield.org/). Оба приложения доступны на платформах Android и iOS, распространяются под открытой лицензией (AGPL-3.0 и GPLv2 соответственно) а так же имеют схожий функционал. В этом разделе будет рассмотено использование связки приложений QGIS - QField для ориентирования на местности и сбора полевых данных.

::: {.callout-note}
## Обратите внимание!
Дополнительную информацию о приложении QField можно получить на сайте проекта ["Картетика"](https://cartetika.ru/tpost/kugvp2hpe1-qfield-qgis-v-mobilnom-prilozhenii).
:::

Связь между QGIS и QField обеспечивает плагин "QField Sync" который устанавливается в программу QGIS (пункт **"Модули" > "Управление модулями..." > поиск модуля "QField Sync"**). 

!! Рис - Плагин QField

Плагин отвечает за настройку проекта, экспорт в QField а так же импорт из QField. Перенос проекта в мобильное приложение QField выполняется в несколько этапов:

+ Создание и настройка проекта в QGIS. На этом этапе выбираются необходимые слои а так же настраиваются их стили отображения.
+ Подготавливаются слои для сбора полевых данных. В зависимости от типа полевых данных это могут быть точечные, линейные или полигональные слои с настроенной таблицей атрибутов. Обычно такие слои создаются пустыми. Они предназначены для сбора полевых данных в QField.
+ Задаются настройки экспорта проекта в плагине "QField Sync". Проект и все файлы сохраняются в отдельную папку.
+ Сохраненный проект копируется на мобильное устройство, после чего производится импорт проекта в QField.

Рассмотрим эти этапы на примере решения задачи: сбор данных о редких видах растений.

::: {.callout-note}
## Загрузите файлы!
Для выполнения последующих заданий загрузите файлы по [ссылке 1]():

:::

## Создание нового проекта в QGIS

Новый проект, в ходе выполнения заданий практикума, обучающимися создавался неоднократно, поэтому для этого этапа подробного описания не приводится.

::: {#task-task .callout-tip}
Создайте новую папку проекта и новый проект. Задайте cледующие стили отображения и подписи слоев:

+ каждый выдел должен быть подписан номером выдела;
+ каждый квартал должен быть подписан номером квартала.

Результат выполнения задания приведен на рисунке ниже (!Рисунок)
:::

## Создание слоев для сбора данных

Настройки слоев для сбора полевых данных определяются характером этих данных:

+ выбор типа геометрии собираемых данных (точка, линия, полигон);
+ выбор и настройка собираемых атрибутов.

Рассмотрим ситуацию, когда нам нужно отметить местоположения редких видов растений. Если предполагается что растения произрастают группами, для сбора данных предпочтительно использоваться полигональный слой. Если же растения одиночные - точечный. В таблице атрибутов создается отдельное поле для каждой характеристики растения, это может быть: вид растения; состояние; фотография; поле для комментария.

Для сбора данных создадим новый точечный векторный слой под названием **"points"**. Рекомендуемый формат файла - GeoPackage (.gpkg). Так же создадим в этом слое следующие поля:

+ **"name"**, текстовое - в него будем записывать название вида;
+ **"discript"**, текстовое - в это поле будет записано описание растения (комментарий).

Необходимые поля созданы. Теперь откройте свойства слоя **"points"** > **"Формы полей"** > режим **"Конструктор форм"**. В пункте **"Макет формы"** удалите поле **"fid"**, полю **"name"** задайте псевдоним **"Вид растения"**, полю **"discript"** задайте псевдоним **"Описание"**. Теперь псевдонимы полей будут отображаться вместо изначальных имен полей. Псевдонимы отображаются в таблице атрибутов и приложении QField, это удобный способ дать полям названия на кириллице. Пока ограничимся этими двумя полями (в дальнейшем будут добавлены поля, содержащие дату добавления точки а так же фотографию).

Видео - Конструктор форм

## Экспорт проекта

Вами уже были настроены стили отображения и слои для сбора данных. Осталось настроить экспорт проекта в плагине "QField Sync". Перейдите в пункт **"Модули" > "QField Sync" > "Configure current project"**. В окне доступно две вкладки конфигурирования проекта, в зависимости от способа переноса проекта в мобильное устройство: "QFieldCloud Packaging" - если вы используюте облачный сервер; "Cable Packaging" - при копировании проекта напрямую (не обязательно через проводное соединение). Далее настройки производим во вкладке "Cable Packaging".

Рисунок - Настройки конфигурирования проекта "QField Sync"

В верхней части окна производится настройка для каждого слоя. Возможны 4 режима:

+ "Copy" - слой будет скопирован в новый проект;
+ "Offline editing" - слой будет подготовлен для редактирования;
+ "Remove from project" - слой будет удален из проекта.

Напротив слоя "Points" выберите режим "Offline editing", остальные слои - режим "Copy". Нажмите "ОК". 

Теперь сконфигурируем проект. По сути это будет копия текущего проекта с настройками для мобильного приложения QField. Перейдите в пункт **"Модули" > "QField Sync" > "Package for QField"**, выберите папку для сохранения проекта и нажмите **"Create"**. Копия проекта, сконфигурированная для использования в QField, будет сохранена в указанную папку.

## Импорт проекта в QField

Сконфирурированную копию проекта необходимо скопировать на мобильное устройство. Далее работа проводится на мобильном устройстве. Откройте приложение QField > "Открыть локальный файл" > иконка "+" в правом нижнем углу > "Импорт проекта из папки" (указать папку в которую был скопирован проект).






